# This Makefile is just here to allow auto-completion in the terminal.

actions = \
	build \
	check \
	check-api \
	check-docs \
	check-quality \
	check-types \
	clean \
	clean_cache \
	coverage \
	{%- if dockerfile %}
	docker-build \
	docker-start \
	docker-stop \
	docker-exec-check \
	docker-exec-check-api \
	docker-exec-check-docs \
	docker-exec-check-quality \
	docker-exec-check-types \
	docker-exec-coverage \
	docker-exec-docs \
	docker-exec-test \
	{%- if tox %}
	docker-exec-tox \
	{%- endif %}
	{%- endif %}
	docs \
	{%- if repository_provider == 'github' %}
	docs-deploy \
	{%- endif %}
	format \
	{%- if publish_to_pypi %}
	publish \
	{%- endif %}
	{%- if with_conventional_commits %}
	release \
	{%- endif %}
	setup \
	setup-dev \
	test {% if tox %}\
	tox
	{%- endif %}


.PHONY: $(actions)
$(actions):
	@uv run duty "$@"


.PHONY: help
help:
	@uv run duty --list

.DEFAULT_GOAL := help
