# This Makefile is just here to allow auto-completion in the terminal.

actions = \
	audit \
	build \
	check-all \
	check-quality \
	check-security \
	check-types \
	clean-all \
	clean-cache \
	coverage \
	{%- if with_doppler %}
	dc \
	{%- endif %}
	{%- if dockerfile %}
	docker-build \
	docker-shell \
	docker-start \
	docker-stop \
	{%- endif %}
	docs-check \
	docs-serve \
	{%- if repository_provider == 'github' %}
	docs-deploy \
	{%- endif %}
	format \
	{%- if publish_to_pypi %}
	publish \
	{%- endif %}
	{%- if with_conventional_commits %}
	release \
	{%- endif %}
	setup-prod \
	{%- if with_typer_cli %}
	setup-cli \
	{%- endif %}
	setup-dev \
	test{% if tox %}\
	tox
	{%- endif %}\
	upgrade


.PHONY: _check-mise
_check-mise:
	@command -v mise >/dev/null 2>&1 || { echo "Error: mise is not installed. See https://mise.jdx.dev/getting-started.html"; exit 1; }

.PHONY: $(actions)
$(actions): _check-mise
	@mise run "$(subst -,:,$@)"

{%- if with_doppler %}
doppler_actions = \
	doppler-create-config \
	doppler-create-token \
	doppler-set-token \
	doppler-delete-config \
	doppler-upload-secrets

.PHONY: $(doppler_actions)
$(doppler_actions): _check-mise
	@mise run "doppler:$(patsubst doppler-%,%,$@)"
{%- endif %}

.PHONY: mise-setup-completions
mise-setup-completions: _check-mise
	@mise run "mise:setup-completions"

.PHONY: pre-commit
pre-commit: _check-mise
	@mise run "pre-commit"


.PHONY: help
help: _check-mise
	@mise tasks

.DEFAULT_GOAL := help
