#!/bin/bash

# Get the root of the git repo
REPO_ROOT=$(git rev-parse --show-toplevel)

COMMIT_MSG_FILE="$1"

if [[ -f "$COMMIT_MSG_FILE" ]]; then
    COMMIT_MSG=$(<"$COMMIT_MSG_FILE")

    # If message contains "dumb commit", skip the script
    if [[ "$COMMIT_MSG" == *"dumb commit"* ]]; then
        echo "Skipping hook due to 'dumb commit' in message."
        exit 0
    fi
fi

uv run "$REPO_ROOT/scripts/git-hooks/prepare-commit-msg.py" "$@"
