default_install_hook_types:
  - pre-push
  - commit-msg

repos:
- repo: https://github.com/commitizen-tools/commitizen
  rev: v4.6.0
  hooks:
  - id: commitizen
    language: python
    additional_dependencies:
      - cz-conventional-gitmoji

    stages:
    - commit-msg
  - id: commitizen-branch
    language: python
    additional_dependencies:
      - cz-conventional-gitmoji
    stages:
    - pre-push

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v5.0.0"
  hooks:
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-toml
    - id: check-yaml
      exclude: ^mkdocs\.yml$
    - id: check-json
    - id: check-added-large-files
    - id: detect-private-key
    - id: pretty-format-json
      args: [--autofix, --no-sort-keys]
    - id: end-of-file-fixer
    - id: trailing-whitespace
