default_install_hook_types:
  - pre-push
  - commit-msg

repos:
- hooks:
  - id: commitizen
    additional_dependencies: [cz-conventional-gitmoji]
    stages:
    - commit-msg
  - id: commitizen-branch
    additional_dependencies: [cz-conventional-gitmoji]
    stages:
    - pre-push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v4.5.1
