name: 'Setup UV & Python'
description: 'Checks out the repo, sets up `uv`, and installs the right Python version (supports file or literal).'
inputs:
  python-version:
    description: 'Literal Python version (e.g. "3.12")'
    required: false
  python-version-file:
    description: 'Path to a .python-version file'
    required: false

runs:
  using: composite
  steps:
    - name: Setup uv
      uses: astral-sh/setup-uv@f0ec1fc3b38f5e7cd731bb6ce540c5af426746bb # v6

    - name: Setup Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
      with:
        # one of these two
        python-version: ${{ inputs.python-version }}
        python-version-file: ${{ inputs.python-version-file }}
