name: release

on: push

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Setup uv
      uses: astral-sh/setup-uv@v5

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Prepare release notes
      run: uvx --from commitizen --with cz-conventional-gitmoji cz changelog ${{ github.ref_name }} --file-name release-notes.md

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        body_path: release-notes.md
